[package]
name = "rustAlloy"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.17", features = ["full"] }
tokio = { version = "1.46.1", features = ["rt", "rt-multi-thread", "macros"] }
